"""initial schema

Revision ID: e113e3d3fb28
Revises: 
Create Date: 2026-04-13 16:04:33.339884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e113e3d3fb28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('personality', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_a_id', sa.UUID(), nullable=False),
    sa.Column('agent_b_id', sa.UUID(), nullable=False),
    sa.Column('conversation', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Enum('match', 'rejection', 'situationship', 'ghosted', name='outcomeenum'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_a_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['agent_b_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dates')
    op.drop_table('agents')
    # ### end Alembic commands ###
